Add a "completion" screen to the onboarding
Automattic/newspack-plugin pull request #1377
Opened 2021-12-17 17:40 UTC by thomasguillot

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates a bunch of components and most importantly, add a completion screen at the end of the onboarding. This allows users to choose what they want to do once they are done instead of being redirected to the dashboard and not knowing what to do.

![Screenshot 2021-12-17 at 17 30 40](https://user-images.githubusercontent.com/177929/146585291-7d25c543-8270-48d7-bc0c-4a93a1191932.png)

I've also reorganised the welcome screen a bit so both screen kind of match

![Screenshot 2021-12-17 at 17 30 25](https://user-images.githubusercontent.com/177929/146585351-dc4ea857-374c-4022-bc92-c8ef8d6f081c.png)

### How to test the changes in this Pull Request:

1. Switch to this branch
2. Go through the Setup

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-01-12 19:00 UTC, dkoo requested changes
A couple of non-blocking code style suggestions, and one blocking bug that prevented me from actually completing setup.

2022-01-12 19:00 UTC, dkoo commented on assets/wizards/setup/views/completed/index.js
> +								{ __( 'Go to Dashboard', 'newspack' ) }
This is the blocking bug that we need to fix before we can proceed.

2022-01-13 13:57 UTC, thomasguillot commented on assets/components/src/footer/index.js
>  	const componentsDemo = window && window.newspack_urls && window.newspack_urls.components_demo;
https://github.com/Automattic/newspack-plugin/pull/1377/commits/412655c206415a39c2e06b3e30beb068d456a4e6

2022-01-13 15:41 UTC, thomasguillot commented on assets/wizards/setup/views/completed/index.js
> +								{ __( 'Go to Dashboard', 'newspack' ) }
I attempted to fix this here: https://github.com/Automattic/newspack-plugin/pull/1377/commits/d238f1fd680361a71169361f41fa419e3d40bc95

Not sure if this is ok. If it's not then I could use some help 🙂

2022-01-13 18:25 UTC, dkoo commented on assets/wizards/setup/views/completed/index.js
> +								{ __( 'Go to Dashboard', 'newspack' ) }
@thomasguillot This seems to have worked when I tested on a new JN site. Thanks!

2022-01-13 18:26 UTC, dkoo approved these changes
@thomasguillot I updated the branch with `master` and fixed merge conflicts—could you do one more round of functional testing on your end to make sure the merge went okay, then if it looks 👍 to you I think this is good to go.

2022-01-14 09:53 UTC, thomasguillot commented
@dkoo thank you so much for this. It looked good. I just added a very small fix to the mailchimp error message in https://github.com/Automattic/newspack-plugin/pull/1377/commits/1f11048792668eb04a1ab62a60513de34a58568d and https://github.com/Automattic/newspack-plugin/pull/1377/commits/dc1de65d2b09d63ebf22f8b727a44d9fa2bf52d9

2022-01-14 10:13 UTC, merged