fix: remove wordads and adsense integration
Automattic/newspack-plugin pull request #1465
Opened 2022-01-24 20:04 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Removes WordAds and AdSense integration from Setup and Ads wizards.

![image](https://user-images.githubusercontent.com/820752/150855758-20d5c4a7-3756-413a-9d6a-f450fe9df0d4.png)

![image](https://user-images.githubusercontent.com/820752/150855857-45e61f96-f3f9-44cb-a3f4-0aaf39eed06e.png)

Closes https://github.com/Automattic/newspack-ads/issues/249.

### How to test the changes in this Pull Request:

1. Visit Advertising home wizard and WordAds and AdSense should no longer be available as options
2. Start a new site, complete the onboarding setup and confirm the Google AdSense was not an available "extra feature"

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-01-25 13:59 UTC, adekbadek commented
Now that it's just one provider, this screen does not make much sense. The tab should rather be called "Google Ad Manager" and the view visible after clicking "Configure" should be the content of this tab. Also, it now makes no sense to "turn on" GAM as a provider, since this is the only option.  

![image](https://user-images.githubusercontent.com/7383192/150990438-57775dba-7db3-47d4-84eb-3ee473dde03d.png)

cc @thomasguillot

2022-01-25 14:42 UTC, miguelpeixe commented
Good call! 11663b27e937c9834db5dd82094196371173970c removes the "Ad Providers" screen and makes GAM Ad Units the home of the wizard. I decided to title it "Google Ad Manager" because of the coming plans with [Ads Milestone 4](https://github.com/Automattic/newspack-ads/milestone/4) and further GAM integration.

2022-01-25 16:27 UTC, thomasguillot commented
Changes look good, thank you @miguelpeixe

2022-01-26 17:46 UTC, miguelpeixe commented
I realized that there are functionalities tied to the toggling of the GAM service. This means that even though we do not have other providers, GAM should still be able to be activated and deactivated.

4324f8ddde01b3db591009f1b64a41e294d626d5 restores the `<ActionCard />` but keep the rest of GAM configuration on the same screen.

![image](https://user-images.githubusercontent.com/820752/151217833-97d4b001-86cd-4b5d-be4d-76f308f39c36.png)

![image](https://user-images.githubusercontent.com/820752/151217886-961c644e-c24a-480b-af76-7ba7037b14b4.png)

2022-01-28 10:10 UTC, adekbadek commented
Option 1 – I like @thomasguillot 's suggestion, I'd only move the the "Google Ad Manager" tab to the last position, since it should be the least used tab. With GAM deactivated, it should be the only tab (which means there can be no tabs at all).

Option 2 – That said, I think @miguelpeixe 's solution is fine, with the first tab name changed to "Ad Units", since that's the main purpose of it. And the action card with the toggle could be moved to "Settings" tab, since this toggle should be used once in most cases. 

I'd say let's do option 1, but if that'd take too much dev resources, option 2 + an "enhancement" issue on GH for option 1 is fine. WDYT?

2022-01-28 17:33 UTC, miguelpeixe commented
cc @kmwilkerson, in case you have ideas as well 😃

2022-01-31 12:15 UTC, thomasguillot commented
Here's what we could do:

- The tab could be called "Ad Dashboard" or whatever is best
- On init, you'd have the GAM toggle disabled. (unless it was already enabled during the onboarding)
- Once you enable the toggle, the "Ad Dashboard" would display "Ad Units", "Order & Line Items", etc... and then the GAM toggle, alongside the network code would move to the "Settings".

2022-01-31 13:04 UTC, miguelpeixe commented
> Once you enable the toggle, the "Ad Dashboard" would display "Ad Units", "Order & Line Items", etc...

Would we use a `<Card />` to link to the ad units? We won't have orders and line items just yet.

2022-01-31 13:29 UTC, thomasguillot commented
`buttobcard` like the dashboard wizard

2022-01-31 13:39 UTC, miguelpeixe commented
That also means the ads wizard home wouldn't be consistent. What would we put as home in case GAM is deactivated? 🤔

2022-03-15 20:08 UTC, miguelpeixe commented
Tagging @adekbadek @thomasguillot, since this has been on hold for a while and is ready for review again

2022-03-16 15:07 UTC, thomasguillot commented
> Tagging @adekbadek @thomasguillot, since this has been on hold for a while and is ready for review again

Looking good. I moved GAM's `ActionCard` to be at the top. https://github.com/Automattic/newspack-plugin/pull/1465/commits/c4e3302b43967c7566349fc49b572521e98bb28b

2022-03-21 21:04 UTC, dkoo requested changes
Functionally, looks 👍 to me. A few nitpicks below:

2022-03-22 13:36 UTC, miguelpeixe commented on assets/wizards/advertising/views/ad-unit/index.js
> +					<Button isSecondary href="#/">
Nice catch! While testing different flows I changed it and forgot to change it back. aad971cc764ba43541aa0f1725a6f3b8e94003ef fixes it.

2022-03-22 13:37 UTC, miguelpeixe commented on assets/wizards/advertising/index.js
> +				label: __( 'Providers', 'newspack' ),
I think "Back" is enough. Done in e793f74a6ca9b9a5c0566286d36403d72ad6d077

2022-03-22 16:24 UTC, dkoo approved these changes
Thanks for the changes—looking good to me now!

2022-03-22 16:59 UTC, merged