Add/fivetran amendments
Automattic/newspack-plugin pull request #1470
Opened 2022-01-26 14:58 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add handling of a column- and table-blocking scenario to Fivetran interaction. Testing steps in https://github.com/Automattic/newspack-manager-client/pull/16

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-02-08 17:59 UTC, dkoo requested changes
I'm not sure this is a problem, but when comparing the schema in Fivetran to the data model outlined in the doc, I see some discrepancy.

In Fivetran:

<img width="658" alt="Screen Shot 2022-02-08 at 10 47 54 AM" src="https://user-images.githubusercontent.com/2230142/153045924-e8bee74b-5993-462a-b8b3-0b9f3d76a025.png">

According to the doc:

<img width="647" alt="Screen Shot 2022-02-08 at 10 48 50 AM" src="https://user-images.githubusercontent.com/2230142/153045989-86d9d3d7-a3a7-4ba6-b39c-20e78b3e0cb0.png">

The `member`, `segment`, and `unsubscribe` tables are listed as used in the docs, but are disabled within Fivetran.

2022-02-14 15:43 UTC, miguelpeixe approved these changes
It's working as described! I was not able to reproduce the issue reported by @dkoo.

Left a couple of requests and should be ok to merge after these small adjustments.

2022-02-14 15:43 UTC, miguelpeixe commented on includes/oauth/class-fivetran-connection.php
>  		if ( is_wp_error( $connections_stauses ) ) {
```suggestion
		$connections_statuses = self::process_proxy_response(
			\wp_safe_remote_get(
				$url,
				[
					'timeout' => 30, // phpcs:ignore WordPressVIPMinimum.Performance.RemoteRequestTimeout.timeout_timeout
				]
			)
		);
		if ( is_wp_error( $connections_statuses ) ) {
```

2022-02-14 16:15 UTC, miguelpeixe commented on includes/oauth/class-fivetran-connection.php
>  			return new WP_Error(
This is actually not necessary! You skip this one.

2022-02-15 08:51 UTC, adekbadek commented
Merged to `release` as a hotfix (https://github.com/Automattic/newspack-plugin/pull/1515) – these changes are now on `master` (https://github.com/Automattic/newspack-plugin/commit/bd76ceab7c9359a47c91a0b25287b41cf0e421b4)

2022-02-15 08:51 UTC, closed without merging