Feat/ac metadata subs
Automattic/newspack-plugin pull request #1859
Opened 2022-08-05 12:17 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

A few related updates to how Stripe & ESP metadata integration work:

- removes explicit Stripe webhook re-creation, with implicit (behind the scenes) webhook creation and reset
- adds handling of subscription update and cancellation events in the Stripe webhook
- adds subscription-related metadata to ESP integration
- removes ability to pause a subscription via the Stripe billing portal

### How to test the changes in this Pull Request:

1. Start with a site with Stripe, ActiveCampaign as ESP, and Reader Activation configured
2. Make a new recurring donation as a reader
3. Observe that the following fields are added in AC:
    - `NP_Current Subscription Start Date`
    - `NP_Current Subscription End Date` (`-` initially or if subscription cancelled)
    - `NP_Membership Status` – `Donor` for one-time donations, `<Montly|Yearly> Donor` for recurring, with `Ex-` suffix if subscription cancelled
4. Visit My Account -> Billing page, and proceed to Stripe customer portal
5. Observe the subscription can be cancelled, but not paused
6. Cancel the subscription (it will be _scheduled_ to be cancelled), observe the `NP_Current Subscription End Date` field updated accordingly
7. In Stripe dashboard, cancel the subscription immediately
8. Observe the `NP_Membership Status` field updated accordingly

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-08-09 03:11 UTC, dkoo requested changes
This isn't working for me. A few issues:

1. Upon making a donation, after ActiveCampaign gets the contact's info, I can see the new fields in the contact page, but none of the recurring donation fields contains any values:

<img width="683" alt="Screen Shot 2022-08-08 at 9 03 06 PM" src="https://user-images.githubusercontent.com/2230142/183554642-2bb2de7c-3a4a-473a-b7e2-d853dbe64a3d.png">

2. In the screenshot, also note that the `NP_Current Subscription Start Date` and `NP_Current Subscription End Date` fields appear under the "General Details" category instead of under "Newspack" with the rest of our custom metadata fields.

2. At this stage:

> 4. Visit My Account -> Billing page, and proceed to Stripe customer portal
> 5. Observe the subscription can be cancelled, but not paused

I'm able to pause the subscription. If I first click "Cancel", I'm presented with the option to pause instead of canceling. I'm not sure this is an issue, though, because pausing a subscription is a legitimate reader story:

<img width="527" alt="Screen Shot 2022-08-08 at 9 08 23 PM" src="https://user-images.githubusercontent.com/2230142/183555212-42d9bb4f-f5ae-4b07-a919-999f54efb507.png">

2022-08-11 18:02 UTC, dkoo requested changes
I took another look at this and think I found the reason why many of my test donors didn't get any metadata updated via the Stripe webhooks.

I still can't figure out why the `NP_Current Subscription Start/End Date` fields are appearing under the wrong group, but I can confirm that they're receiving data, at least.

2022-08-15 13:44 UTC, adekbadek commented
> I still can't figure out why the NP_Current Subscription Start/End Date fields are appearing under the wrong group, but I can confirm that they're receiving data, at least.

This is not controlled by the API, the groups are set in a drag-and-drop interface in AC UI in Settings -> Manage Fields (`/app/settings/fields/contacts`).

2022-08-15 15:46 UTC, dkoo approved these changes
Meta fields seem to be working now. Approved, as long as we're okay with subscribers still being able to pause their subscriptions as mentioned in the first review.

2022-08-16 06:28 UTC, yogeshbeniwal commented
Pausing subscription can affect accounting data, such as monthly recurring revenue (MRR).

2022-08-16 07:34 UTC, adekbadek commented
> as long as we're okay with subscribers still being able to pause their subscriptions as mentioned in the first review.

Ah, forgot about that! Fixed in 6a7af3bb88dbdc69026901786f743c26695e09d6

2022-08-16 16:20 UTC, dkoo approved these changes
Confirmed that I can no longer pause my subscription 👍

2022-08-17 07:55 UTC, merged