feat: move have account text below SSO and adjust font-size
Automattic/newspack-plugin pull request #1917
Opened 2022-08-18 14:37 UTC by thomasguillot

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR moves the "Already have account? Sign in" text right below the SSO/Email input section. Leaving the T&C at the bottom.
It also tweaks the font-size and margins.

Closes https://app.asana.com/0/1202719992789620/1202733224125062/f

### How to test the changes in this Pull Request:

1. Switch to this branch
2. Check if "Already have account? Sign in" still works

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-08-18 16:06 UTC, thomasguillot commented on assets/blocks/reader-registration/style.scss
> +			font-size: 0.6875em !important;
Yes. It's to match the Sign in modal.

_Note: Pico is using 12px for this messaging. We are using 11px due to our own vertical rhythm._

2022-08-19 07:21 UTC, adekbadek requested changes

2022-08-19 07:21 UTC, adekbadek commented on assets/blocks/reader-registration/style.scss
> +			font-size: 0.6875em !important;
In the editor, it's `8.8px`. Possibly due to some font-size inheritances:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/7383192/185565510-6e3432a8-faf2-42bf-935d-b7d2ce3e69ea.png">

2022-08-19 11:07 UTC, thomasguillot commented
> In the editor, it's 8.8px. Possibly due to some font-size inheritances:

@adekbadek fixed in https://github.com/Automattic/newspack-plugin/pull/1917/commits/797b7705f8f294c59243b72648cd8f6436081366

2022-08-19 15:58 UTC, adekbadek approved these changes

2022-08-22 08:08 UTC, merged