fix: allow Register block to be edited even if RAS is not enabled
Automattic/newspack-plugin pull request #1962
Opened 2022-08-31 17:23 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Currently, the Register is only available in the editor if experimental Reader Activation features are enabled via both an environment constant and a Newspack dashboard setting. However, for transitioning live publisher site to a Reader Activation model, we need to be able to set up registration prompts and flows prior to activating the features. This PR makes the block available and editable in the editor, but ensures that the block is not rendered and its assets not enqueued on the front-end unless the features are enabled.

### How to test the changes in this Pull Request:

1. Check out this branch.
2. In Newspack > Engagement > Reader Activation, turn off Reader Activation with the checkbox and save.
3. Edit a post, page, or prompt and confirm that you can still add a Reader Registration block, update it, save, etc.
4. View the block on the front-end and confirm that it renders nothing, and that its CSS and JS files are not enqueued.
5. Re-enable Reader Activation, view the block on the front-end, and confirm that it now renders as expected with all changes you made in the editor.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-08-31 20:06 UTC, miguelpeixe requested changes
Works as described!

I'm hesitant to have a block available that doesn't work unless you enable a feature somewhere else. Can we make it unlisted in the block library when RAS is off?

2022-08-31 20:59 UTC, dkoo commented on assets/blocks/reader-registration/index.php
> +	if ( ! Reader_Activation::is_enabled() || ! isset( $_REQUEST[ FORM_ACTION ] ) || ! \wp_verify_nonce( \sanitize_text_field( $_REQUEST[ FORM_ACTION ] ), FORM_ACTION ) ) {
Done in bf8f97d

2022-08-31 21:19 UTC, dkoo commented
> I'm hesitant to have a block available that doesn't work unless you enable a feature somewhere else. Can we make it unlisted in the block library when RAS is off?

That's a good point, and we shouldn't be allowing sites to add the block that don't have the environment constant enabled. e2cd9f6 implements a `$strict` param in the `Reader_Activation::is_enabled` method that's `true` by default, but if it's `false` then we only check for the constant and ignore the setting. This will let us add and edit the block for the beta sites without fully activating RAS features, but won't show the block for non-beta sites.

2022-09-01 20:13 UTC, miguelpeixe approved these changes

2022-09-01 20:13 UTC, merged