Feat/author fields
Automattic/newspack-plugin pull request #2102
Opened 2022-11-01 12:00 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #1723

### How to test the changes in this Pull Request:

1. Set Newspack Blocks to `feat/author-blocks-fields` branch 
2. Set Newspack Theme to `feat/author-custom-fields` branch
1. Ensure you have some regular and Co-Authors Plus (guest) authors on the site
1. Insert an Authors List block and two Author Profile blocks on a page
3. Set the list block to display both guest and regular authors
4. Set the profile blocks to display a regular and a guest author
5. View the editor and the front-end, verify nothing is broken
6. Edit the WP author, add some values in the "Additional user profile fields" section
7. Edit the guest author, add some values in new fields in the "About the guest author" section 
8. Again, view the page in the editor and on the front-end and see that field values are reflected there
9. View a post by the guest author and one by the WP author, see that the "Job Title" value is displayed in the author bio footer, next to the name

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-11-01 20:19 UTC, leogermani requested changes
It works as expected except from one issue

Editing guest author is fine, but the extra fields for regular users only show up if I'm editing another user other than myself.

To display and save the extra fields when editing your own profile, you must use `show_user_profile`  and `personal_options_update` hooks.

Also, not sure if this is related to this PR, but the link in the "More by __author__" in the blocks use the `?author_name=$name` format instead of the pretty permalink. Any reason for that? The same link looks fine in the Footer bio when you visit a post.

2022-11-02 13:48 UTC, adekbadek commented
> Editing guest author is fine, but the extra fields for regular users only show up if I'm editing another user other than myself.

Thanks for catching that! Fixed in c72631b2bb8eafab2c966093fe975a5018966887

> the link in the "More by author" in the blocks use the ?author_name=$name format instead of the pretty permalink. Any reason for that? 

This is not something this PR touches. It is like that [only for guest authors](https://github.com/Automattic/newspack-blocks/blob/7ccd995e580523b2b94117cb3cad50d5504cbb65/src/blocks/author-profile/class-wp-rest-newspack-authors-controller.php#L256) – maybe they are not guaranteed to have a permalink, because there might be name collisions with a WP user.

2022-11-02 14:26 UTC, leogermani approved these changes

2022-11-03 10:12 UTC, adekbadek commented
Waiting with the merge for approval on the related [Blocks](https://github.com/Automattic/newspack-blocks/pull/1302) and [Theme](https://github.com/Automattic/newspack-theme/pull/1966) PRs, because all three should be released as a single feature-set.

2022-11-03 16:35 UTC, merged