feat(stripe-sync-cli): create WC subscriptions
Automattic/newspack-plugin pull request #2180
Opened 2022-12-08 14:11 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

When the CLI command for synchronising Stripe data to WC was created (#1981), the Stripe-to-WC-Subscriptions functionality (#1936) was not ready yet. For this reason, the CLI command will not create WC Subscriptions and a series of one-time charges will be created instead.

This PR updates the CLI command, so that WC Subscriptions are created for corresponding Stripe Subscriptions. 

### How to test the changes in this Pull Request:

1. Ensure your Stripe instance has at least:
    1. one one-time donation charge, not synced to WC
    2. one one-time donation charge, synced to WC*
    3. one donation subscription, not synced to WC
    4. one donation subscription, synced to WC
    5. one-time donation made via WC**
    6. recurring donation made via WC**
7. Run `wp newspack stripe sync-customers --sync-to-wc` 
8. Observe that (from pt. 1):
    - 1., 3. were synced to WC
    - 2., 4. were not (there were already there)
    - 5., 6. are still there
    - new customers were created where applicable

\* Made with Stripe as Reader Revenue platform and WC suite active. Ensure webhook is configured and can reach your site. 
\** Set the Reader Revenue platform to Newspack and make a donation via WC checkout using Stripe Gateway (configured to use the same Stripe instance). The important bit is that WC Stripe Gateway will set `order_id` meta on the Stripe charge. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-12-14 01:51 UTC, dkoo requested changes
This works as long as your Stripe instance is using the correct API version. There are a couple of minor error-handling issues below, otherwise this seems to do the job. 👍 

One question about the intended functionality: if your site has Stripe donations enabled, but not RAS, if you turn on RAS and run the sync, should it sync those customers, orders, and subscriptions? I'm not seeing that happen. How I tested:

* Temporarily turned off RAS and disabled Woo
* Made a recurring donation via the Stripe donation block
* Turned on RAS and re-enabled Woo
* Ran the CLI script—it created the customer and the order, but not a matching subscription

2022-12-14 14:28 UTC, adekbadek commented on includes/reader-revenue/stripe/class-stripe-sync.php
> +		$last_payments = Stripe_Connection::get_customer_transactions( $customer->id, false, 1 );
Good call, added more checks in 59d8f6817dfb3d7d64fd39d108230a3e336defc0

2022-12-14 14:47 UTC, adekbadek commented
> if your site has Stripe donations enabled, but not RAS, if you turn on RAS and run the sync, should it sync those customers, orders, and subscriptions? I'm not seeing that happen. 

Whoa, great catch! Fixed in 8f95e50880f7b073a97e5c0349789f17a3138d06. The user ID is needed to created a WC subscription, and it was not set in the sync code. It falls back to the ID found in the customer metadata, but without RAS, the users accounts are not created and thus the customer does not have a user ID in the metadata.

2022-12-14 21:21 UTC, dkoo approved these changes
Confirming that after 8f95e50, the missing subscriptions are created and linked. 👍 

Approving because I'm again not sure whether this is an issue, but I noticed after running the script a second time on the same site (to test 8f95e50) all the orders were synced again, meaning I have two sets of the same orders. Is this expected because we only intend to run this once per site?

2022-12-15 10:48 UTC, adekbadek commented
This is not expected, the sync will not create an order if an order with the stripe charge ID is found. This must be because of [this change](https://github.com/Automattic/newspack-plugin/commit/8f95e50880f7b073a97e5c0349789f17a3138d06#diff-e023ead978ecfc778ee839a92bc06b024da375a0efe42626ace625d60c9bc2c8L71-R72). Erroneously, invoice ID was set as the charge ID previously, so the orders with invoice ID as the charge ID would have been duplicated on the second run.

2022-12-15 10:48 UTC, merged