feat(my-account): display stripe billing link regardless of RR platform
Automattic/newspack-plugin pull request #2278
Opened 2023-02-13 13:03 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Current behavior: The Stripe billing portal link is only shown if Stripe is the current active Reader Revenue platform. This means if the platform was Stripe at one point but subsequently changed, readers who donated via Stripe can no longer self-serve their own subscription management.

Desired behavior: Rather than tie the portal link to the active RR platform, the logic should check whether the currently logged-in reader has any Stripe subscriptions associated with their account.

Closes 1203869877018965-as-1203870488073009

### How to test the changes in this Pull Request:

1. On `master`,
1. Set RR platform to Stripe and make a recurring donation. Log to "My Account" page 
2. Observe the "Billing" link is among the menu items
3. Switch RR platform to Newspack
4. As the logged-in donor, observe the "Billing" item is missing
5. Switch to this branch, reload the page – observe the "Billing" item is there

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-02-14 17:13 UTC, miguelpeixe requested changes
Using the new logic the customer with a Stripe subscription but under the "Newspack" platform will also have their WooCommerce links removed (Addresses and Downloads).

Perhaps it should be decoupled so there's a method to handle each context (Stripe subscription exists vs. Stripe is the defined platform).

2023-02-15 12:10 UTC, adekbadek commented
> Using the new logic the customer with a Stripe subscription but under the "Newspack" platform will also have their WooCommerce links removed (Addresses and Downloads).

This is independent of the platform – hiding these fields is a RAS feature. Before, it was assumed that RAS & Stripe RR platform go together, but we've since made RAS compatible with WooCommerce.

2023-02-16 09:53 UTC, miguelpeixe approved these changes

2023-02-16 09:55 UTC, miguelpeixe commented
We might want to revisit this now that WC is supported on RAS. "Addresses" is a standard page for editing your billing information. Non-blocking for this PR, though

2023-02-16 11:27 UTC, merged