Unify on-site RR platforms (deprecate Stripe as a separate platform)
Automattic/newspack-plugin pull request #2315
Opened 2023-03-03 10:27 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Unifies on-site Reader Revenue platforms, so that "Newspack" is the only one. 

This is a breaking change. Recurring donations will no longer result in Stripe Subscriptions – instead, WC Subscriptions will be created. If Stripe was set as the Reader Revenue platform, it will be changed to Newspack.  

### How to test the changes in this Pull Request:

1. On `master`, configure Stripe as the Reader Revenue platform
2. Switch to this branch
3. Observe the Reader Revenue platform in the Reader Revenue wizard is now set to "Newspack"
4. Ensure that "Stripe – Credit Card (Stripe)" is the only payment method enabled in WC*
5. Visit the front-end page with a Donate block – observe the same UI as with the Stripe RR platform
6. Make a recurring donation and then a one-time donation
7. Observe both processed in Stripe (in [Stripe Dashboard](https://dashboard.stripe.com/dashboard)) as single transactions 
8. Observe the recurring donation has resulted in a WC Subscription, and the one-time donation in a single order

\* `/wp-admin/admin.php?page=wc-settings&tab=checkout` 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-01-04 17:55 UTC, dkoo commented
@adekbadek time to update this one to the latest `master`?

2024-01-16 23:03 UTC, dkoo requested changes
Saw some issues and fatals during testing that I think could be resolved after fixing conflicts created by #2821. Also want to make sure that any code we're removing in this and https://github.com/Automattic/newspack-blocks/pull/1638 that are still used by our subscription migration tools are fully migrated to that repo. I see some methods and constants being removed here that are still referenced from over there.

2024-01-17 09:21 UTC, adekbadek commented on includes/reader-revenue/woocommerce/class-woocommerce-connection.php
> -	public static function get_order_item( $frequency = 'once', $amount = 0, $product_sku = null ) {
Added to migration tools PR 👌

2024-01-17 09:22 UTC, adekbadek commented on includes/reader-revenue/woocommerce/class-woocommerce-connection.php
> +		\add_action( 'woocommerce_order_status_changed', [ __CLASS__, 'handle_order_status_change' ], 10, 4 );
Removed in bf349a64ce122a9c78edc3ec6eadb261c41441a3

2024-01-17 09:22 UTC, adekbadek commented on includes/reader-revenue/woocommerce/class-woocommerce-connection.php
> +		\Newspack\Google_Services_Connection::send_custom_event(
Removed in bf349a64ce122a9c78edc3ec6eadb261c41441a3

2024-01-17 09:24 UTC, adekbadek commented on includes/reader-revenue/woocommerce/class-woocommerce-connection.php
> +			$frequency    = $subscription->get_billing_period();
Yes, removed in bf349a64ce122a9c78edc3ec6eadb261c41441a3

2024-01-17 09:28 UTC, adekbadek commented on includes/configuration_managers/class-woocommerce-configuration-manager.php
> -			'allow_covering_fees_label'   => get_option( 'newspack_donations_allow_covering_fees_label', '' ),
Good catch! Added in 83f627675e6a38ab1c55a0edbb1d8402fa971b24

2024-01-20 00:30 UTC, dkoo approved these changes
Looking good now and working well!

2024-01-22 15:28 UTC, merged