feat(reader-data): check newsletter subscription on login
Automattic/newspack-plugin pull request #2619
Opened 2023-08-24 19:23 UTC by miguelpeixe

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-08-29 23:33 UTC, dkoo requested changes
This is working with the suggested change.

2023-08-29 23:33 UTC, dkoo commented on includes/reader-activation/class-reader-data.php
> +		$subscribed_lists = \Newspack_Newsletters_Subscription::get_contact_lists( $email_address );
```suggestion
		$subscribed_lists = \Newspack_Newsletters_Subscription::get_contact_lists( $data['email'] );
```

2023-08-30 01:01 UTC, miguelpeixe commented
Nice!

2023-08-30 20:08 UTC, dkoo approved these changes

2023-08-30 20:13 UTC, merged