feat(ads): marketplace settings wizard
Automattic/newspack-plugin pull request #2628
Opened 2023-09-04 15:35 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Details and instructions at https://github.com/Automattic/newspack-ads/pull/718

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-09-06 23:14 UTC, dkoo requested changes

2023-09-12 14:38 UTC, miguelpeixe commented on assets/wizards/advertising/views/marketplace/settings/index.js
> +				console.log( err );
Yep! Thanks for catching that, updated in a64d3955d740701976d294b824e45847f083d225

2023-09-12 14:38 UTC, miguelpeixe commented on assets/wizards/advertising/views/marketplace/settings/index.js
> +		apiFetch( {
Good call! Updated in a64d3955d740701976d294b824e45847f083d225

2023-09-20 22:11 UTC, dkoo approved these changes
Works well!

2023-09-20 22:17 UTC, merged