fix(my-account): fixes for My Account
Automattic/newspack-plugin pull request #2904
Opened 2024-02-03 00:38 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes a few bugs affecting My Account.

### How to test the changes in this Pull Request:

#### Can't renew subscriptions from the Subscription page

1. As a reader, complete a subscription donation and then log into My Account/verify as needed.
2. On `release`, go to My Subscription and click "Renew Now". Observe that you get redirected with no feedback, and the renewal request is never processed.
3. Check out this branch and repeat. Now confirm that you clicking "Renew Now" brings you to a checkout form which you can complete to renew early.

#### Required billing fields for gift recipients

#### Gift recipients can't see "Subscriptions" menu item in My Account

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-02-06 00:52 UTC, dkoo commented
Note: Rebased against `epic/ras-acc` as gift subscription functionality has been fixed in the epic, not in `trunk`.

2024-02-06 16:30 UTC, chickenn00dle requested changes
Hey @dkoo,

I tried testing this but ran into a few issues, with the modal checkout. Not sure if some other changes to `epic/ras-acc` might be conflicting with those in the three PRs that make up these fixes, but am seeing:

1. A fatal related to a missing method in blocks: https://github.com/Automattic/newspack-blocks/pull/1661#discussion_r1480152090
2. And some wonky behavior in the modal checkout preventing me from actually purchasing a gift sub:

https://github.com/Automattic/newspack-plugin/assets/17905991/9fd224bc-193f-4d2e-bada-e9d6a860fee0

2024-02-06 18:04 UTC, dkoo commented
@chickenn00dle looks like the branch needed a merge from the epic. Checkout and gifting should be working again

2024-02-08 18:32 UTC, chickenn00dle approved these changes
Nice! Thanks for clearing that up. This is working as expected now 👍

2024-02-08 18:32 UTC, merged