Feat/add ras welcome email
Automattic/newspack-plugin pull request #3150
Opened 2024-05-30 03:03 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://app.asana.com/0/1207385073694403/1205250932343413/f

This adds a new welcome email template for readers who register via checkout.

### How to test the changes in this Pull Request:

TBA

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-06-04 21:01 UTC, dkoo requested changes
This is working well! I have a few copy suggestions due to the fact that this feature covers more than just donation transactions.

Also, the `*MAGIC_LINK_URL*` placeholder isn't getting populated in the final sent email. We need to fix that auto-replacement as well as include it as a placeholder in the Welcome email config shown in the editor.

 
<img width="1519" alt="Screenshot 2024-06-04 at 3 00 19 PM" src="https://github.com/Automattic/newspack-plugin/assets/2230142/789041db-31d6-4649-8618-a4b60efa7a61">

2024-06-04 21:01 UTC, dkoo commented on includes/reader-revenue/class-reader-revenue-emails.php
> +			'description'            => __( "Email sent to the donor after they've registered while donating.", 'newspack-plugin' ),
In my testing, this doesn't only apply to donations, but to any transaction (this is correct according to the scope of the feature request task). 

```suggestion
			'description'            => __( "Email sent to new reader accounts registered during a transaction.", 'newspack-plugin' ),
```

2024-06-04 21:01 UTC, dkoo commented on includes/reader-revenue/class-reader-revenue-emails.php
> +			'editor_notice'          => __( 'This email will be sent to a reader after they sign up and contribute to your site.', 'newspack-plugin' ),
```suggestion
			'editor_notice'          => __( 'This email will be sent to readers when they register an account during a transaction.', 'newspack-plugin' ),
```

2024-06-05 11:15 UTC, chickenn00dle commented on includes/reader-revenue/class-reader-revenue-emails.php
> +			'description'            => __( "Email sent to the donor after they've registered while donating.", 'newspack-plugin' ),
Good suggestion! Updated in https://github.com/Automattic/newspack-plugin/pull/3150/commits/c58f6399821ce0dcd1262c47d8d609df225e4a42

2024-06-05 11:15 UTC, chickenn00dle commented on includes/reader-revenue/class-reader-revenue-emails.php
> +			'editor_notice'          => __( 'This email will be sent to a reader after they sign up and contribute to your site.', 'newspack-plugin' ),
Also updated in https://github.com/Automattic/newspack-plugin/pull/3150/commits/c58f6399821ce0dcd1262c47d8d609df225e4a42

2024-06-05 11:16 UTC, chickenn00dle commented
Thanks for the review @dkoo!

> Also, the *MAGIC_LINK_URL* placeholder isn't getting populated in the final sent email. We need to fix that auto-replacement as well as include it as a placeholder in the Welcome email config shown in the editor.

This was actually copied over from another template and should not be a verification url. I've updated to a generic account link in https://github.com/Automattic/newspack-plugin/pull/3150/commits/c58f6399821ce0dcd1262c47d8d609df225e4a42

2024-06-06 07:55 UTC, chickenn00dle commented
Related to https://github.com/Automattic/newspack-blocks/pull/1754#issuecomment-2151639952, I added some small changes in https://github.com/Automattic/newspack-plugin/pull/3150/commits/1edca4b99e6b0a57649c23cb2ad8e17bf451176e to deal with a session expired error that appeared for checkout button checkout modal

2024-06-26 20:57 UTC, dkoo approved these changes

2024-06-26 21:03 UTC, merged