Feat/ia settings connections  plugins
Automattic/newspack-plugin pull request #3166
Opened 2024-06-05 02:59 UTC by jaredrethman

Depends on #3163 

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-06-28 19:01 UTC, chickenn00dle requested changes
Hey @jaredrethman,

I tested and was able to confirm the connected state, as well as the error state (by modifying the slug vs path), but had trouble with the uninstall state.

I have everlit uninstalled:
![Screenshot 2024-06-28 at 15 00 33](https://github.com/Automattic/newspack-plugin/assets/17905991/fad972a8-5023-4997-a444-a4b70b45558f)

But it appears to be connected:
![Screenshot 2024-06-28 at 15 00 42](https://github.com/Automattic/newspack-plugin/assets/17905991/5f832a68-4f3d-4b38-a22b-d0c855503716)

2024-06-28 19:01 UTC, chickenn00dle commented on assets/wizards/newspack/views/settings/connections/plugins.tsx
> +		path: '/newspack/v1/plugins/jetpack',
Looks like these paths aren't actually being used by `WizardsPluginCard`. The fetch path seems to be determined by `slug` here: https://github.com/Automattic/newspack-plugin/blob/22f9be9c3bd466bd8274c304b09c7bef03a0eb5e/assets/wizards/wizards-plugin-card.tsx#L27-L38

According to this testing step, it seems as though we are expecting this to be used though:

```
Enforce an error: Update path '/newspack/v1/plugins/jetpack' with '/newspack/v1/plugins/jetpacks'. Update slug jetpack with jetpacks.
```

2024-07-06 03:01 UTC, jaredrethman commented
> Hey @jaredrethman,
> 
> I tested and was able to confirm the connected state, as well as the error state, but had trouble with the uninstall state.

@chickenn00dle thank for the feedback, this is a odd one.

I'm unable to reproduce this. I've tested the following two scenarios:
1. Completing install + activation, then deactivating, then deleting.
2. Completing install + activation, then deleting without deactivating first. 

And in both cases the outcome was the same:
![Screenshot 2024-07-05 at 21 58 21](https://github.com/Automattic/newspack-plugin/assets/3676975/bac020b2-b6f2-4e87-af27-7ac26b1c373e)

Could you please share some minimal reproducible steps and/or test the latest changes and see if the latest code fixes it.

2024-07-06 03:03 UTC, jaredrethman commented on assets/wizards/newspack/views/settings/connections/plugins.tsx
> +		path: '/newspack/v1/plugins/jetpack',
Nice catch, `path` became redundant when I introduced Everlit, I missed the housekeeping step. Have removed `path` in 71ccbd5c5cc8122adcd265b39f514075023de1a1

2024-07-08 16:04 UTC, chickenn00dle commented
> Could you please share some minimal reproducible steps and/or test the latest changes and see if the latest code fixes it.

I pulled the latest changes, but am still seeing the problem 😞 

This seems to happen when the plugin begins as active and connected, but then is disconnected. So to reproduce for Site Kit for example:

1. Make sure site kit is active and connected
2. Pull changes and check connection settings via new settings page
3. Go to plugins and deactivate Site Kit
4. Go back to the connections settings and refresh
5. Site kit appears to still be active

Here is a screen recording if that helps:


https://github.com/Automattic/newspack-plugin/assets/17905991/7da5190d-b8b4-42e3-b480-b806bfef402f

2024-07-08 20:50 UTC, jaredrethman commented
> > Could you please share some minimal reproducible steps and/or test the latest changes and see if the latest code fixes it.
> 
> I pulled the latest changes, but am still seeing the problem 😞
> 
> This seems to happen when the plugin begins as active and connected, but then is disconnected. So to reproduce for Site Kit for example:
> 
> 1. Make sure site kit is active and connected
> 2. Pull changes and check connection settings via new settings page
> 3. Go to plugins and deactivate Site Kit
> 4. Go back to the connections settings and refresh
> 5. Site kit appears to still be active
> 
> Here is a screen recording if that helps:
> 
>  Screen.Recording.2024-07-08.at.11.59.59.mov

Thanks for your response @chickenn00dle , can you confirm the same behavior when `WP_NEWSPACK_DEBUG` const is set to `false`?

If the problem disappears it's because of this code:
https://github.com/Automattic/newspack-plugin/blob/589a4f9f99e761c07339da9aecc9664b74452cae/includes/class-plugin-manager.php#L390-L392

If the problem still persists, we can look into next steps.

2024-07-08 21:26 UTC, chickenn00dle approved these changes
> If the problem still persists, we can look into next steps.

Aha! This was the problem!

Looks good now. Giving this a thumbs up 👍

2024-07-08 21:45 UTC, merged