fix(ras-acc): qa testing design feedback
Automattic/newspack-plugin pull request #3266
Opened 2024-07-23 16:40 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://app.asana.com/0/1207817176293825/1207878733150039, https://app.asana.com/0/1207817176293825/1207878733150043, and https://app.asana.com/0/1207817176293825/1207878733150047

This PR adds various style fixes to RAS-ACC auth form:

1. Spacing between google icon and button text should be 12px:

![Screenshot 2024-07-23 at 12 35 10](https://github.com/user-attachments/assets/5887a254-8e7d-4bd7-bb25-d46788d14a33)

2. Normalize button font styles in newspack ui:

![Screenshot 2024-07-23 at 12 36 07](https://github.com/user-attachments/assets/1bc454da-36dd-4782-b838-d7b204fa9cea)

3. Consistent font weights:

![Screenshot 2024-07-23 at 12 36 58](https://github.com/user-attachments/assets/9c581f14-9156-4639-8352-d7e7f7a81d22)

### How to test the changes in this Pull Request:

1. On a test site, add the following additional CSS via the Appearance > Customize menu:

```
button {	
  border-radius: 0;
  font-size: 0.7rem;
  letter-spacing: 0.1em;
  padding: 1rem 2.5rem;
  text-transform: uppercase;
}
```
2. As a reader trigger the auth modal by clicking the Sign In button at the top right of the page.
3. Verify the 3 points above
  - Spacing between Google G and button text is 12px
  - Button text is not capitalized and custom letter spacing is not being used
  - All font weights for bolded text are 600 

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-07-23 17:45 UTC, laurelfulford requested changes
Thanks for fixing this @chickenn00dle! 

Most of the issues look to be fixed - the only one that's not is the price summary bit -- it's still using the 700 weight:

![image](https://github.com/user-attachments/assets/1cb2f841-e3ed-46bd-868b-eaf2ae4ba18d)

In the PR it looks like the `h2` in the `newspack-ui__modal__header` was targeted for the `600` fotn weight fix -- maybe we can do something more generic where all headings and `strong` tags inside of `.newspack-ui` (or at least `newspack-ui__modal`) use `600`?

2024-07-23 18:15 UTC, chickenn00dle commented
> Most of the issues look to be fixed - the only one that's not is the price summary bit -- it's still using the 700 weight

Just checking, did you also check out https://github.com/Automattic/newspack-blocks/pull/1807 while testing this. That PR renders this text with a paragraph/strong tag instead.

> In the PR it looks like the h2 in the newspack-ui__modal__header was targeted for the 600 fotn weight fix -- maybe we can do something more generic where all headings and strong tags inside of .newspack-ui (or at least newspack-ui__modal) use 600?

This sounds good to me! Done in https://github.com/Automattic/newspack-plugin/pull/3266/commits/d7d5da2226b4acec3afc1277b1900ea07d631ee9

2024-07-23 18:46 UTC, laurelfulford commented
> Just checking, did you also check out https://github.com/Automattic/newspack-blocks/pull/1807 while testing this.

🤦‍♀️ Nope! I missed that step in the testing -- taking a second look!

2024-07-23 19:18 UTC, laurelfulford requested changes
Ok, the more I look at this the more I'm confusing myself!! So please let me know if this doesn't make sense:

The block PR changing the markup from `h2` to `p` does fix the font weight issue but it looks like we have this price header thing coming from two different spots, so it's not fixed everywhere, and my CSS recommendation wasn't specific enough.

If you are not logged in and try to make a donation, [you get the one that's now wrapped in a paragraph tag](https://github.com/Automattic/newspack-blocks/blob/fix/qa-testing-design-feedback/src/modal-checkout/modal.js#L332):

![image](https://github.com/user-attachments/assets/438faf6f-8775-4882-84cc-63d00e4f9d6c)

However, if you are logged in and go right into the checkout flow, [it still uses an `h2` so it's still `700`](https://github.com/Automattic/newspack-blocks/blob/fix/qa-testing-design-feedback/includes/class-modal-checkout.php#L1126-L1132):

![image](https://github.com/user-attachments/assets/0555cf84-984c-4501-bcde-062dbd165928)

The modal checkout doesn't use the `newspack-ui__modal` inside of the iframe, just `newspack-ui__modal__content`, so the more general CSS fix isn't getting picked up there. 

Looking at the Components Figma doc, it uses 400, 600, and 700 weights; 700 is rare but we can't assume it won't be used at all. I think `<p><strong>` is probably the safest fix for both for now, but let me know what you think!

(Sorry this was so long winded! Let me know if you have any questions about this!)

2024-07-24 15:15 UTC, chickenn00dle commented
Thanks for digging into this @laurelfulford!

> However, if you are logged in and go right into the checkout flow, [it still uses an h2 so it's still 700](https://github.com/Automattic/newspack-blocks/blob/fix/qa-testing-design-feedback/includes/class-modal-checkout.php#L1126-L1132):

Aha! Good catch. Pushed up a change in the blocks PR to address this case: https://github.com/Automattic/newspack-blocks/pull/1807/commits/a31d9ca98ec2b5bc5bab7311023794f2fd9770f0

2024-07-24 18:47 UTC, laurelfulford approved these changes
That did it -- thanks @chickenn00dle! 🚢

2024-07-24 19:27 UTC, merged