Feat/ia ads
Automattic/newspack-plugin pull request #3270
Opened 2024-07-24 15:17 UTC by jaredrethman

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-07-30 18:11 UTC, dkoo requested changes
Working as advertised (heh). 

The only thing I caught was the lack of whitespace between the ad units when configuring GAM:

**`trunk`**

<img width="1050" alt="Screenshot 2024-07-30 at 12 07 56 PM" src="https://github.com/user-attachments/assets/504da172-76a8-4100-ab09-703786367430">

**`feat/ia-ads`**

<img width="1044" alt="Screenshot 2024-07-30 at 12 08 11 PM" src="https://github.com/user-attachments/assets/7d900003-7c65-4369-ad81-3aad1311a752">

All other functionality works as expected, except the Plugin cards (e.g. the Configure links after installing—I expect this will be fixed in a future PR since the testing instructions here only mention that they should be appearing in the right place, right).

Something non-blocking I just noticed in this PR but haven't been looking out for: we have a mismatch in some of our translation text domains throughout the Newspack Plugin due to legacy code. The text domain should be `newspack-plugin`, matching the plugin slug, but there are many instances of `newspack` throughout. It's not a blocker at all, but when editing surrounding code I try to update those if I see them. I highlighted all the instances I saw in this changeset, but like I said I don't consider these blockers.

2024-07-30 18:11 UTC, dkoo commented on includes/wizards/advertising/class-advertising-sponsors.php
> +		return esc_html__( 'Sponsors', 'newspack' );
```suggestion
		return \esc_html__( 'Sponsors', 'newspack-plugin' );
```

2024-07-30 18:11 UTC, dkoo commented on includes/wizards/advertising/class-advertising-display-ads.php
> +		return \esc_html__( 'Advertising', 'newspack' );
```suggestion
		return \esc_html__( 'Advertising', 'newspack-plugin' );
```

2024-07-30 18:11 UTC, dkoo commented on includes/wizards/advertising/class-advertising-display-ads.php
> +			$error   = new WP_Error( 'newspack_ad_units', $message ? $message : __( 'Ad Units failed to fetch.', 'newspack' ) );
```suggestion
			$error   = new WP_Error( 'newspack_ad_units', $message ? $message : __( 'Ad Units failed to fetch.', 'newspack-plugin' ) );

2024-08-01 14:34 UTC, jaredrethman commented
@dkoo thanks for the feedback, responses below.

> Working as advertised (heh).

🤣 

> The only thing I caught was the lack of whitespace between the ad units when configuring GAM:

Added back.

> All other functionality works as expected, except the Plugin cards (e.g. the Configure links after installing—I expect this will be fixed in a future PR since the testing instructions here only mention that they should be appearing in the right place, right).

Have added in page anchor navigation.

> Something non-blocking I just noticed in this PR but haven't been looking out for: we have a mismatch in some of our translation text domains throughout the Newspack Plugin due to legacy code. The text domain should be newspack-plugin, matching the plugin slug, but there are many instances of newspack throughout. It's not a blocker at all, but when editing surrounding code I try to update those if I see them. I highlighted all the instances I saw in this changeset, but like I said I don't consider these blockers.

Yeah, I've noticed these too. I've replaced all text domains in the newer stuff, but neglected to do so for the migration of the older stuff. Will keep an eye out for this going forward.

2024-08-02 16:28 UTC, dkoo commented
> Have added in page anchor navigation.

Works well after a page refresh, but since some of the settings sections aren't rendered if we don't have the plugin requirements, if you click "Configure" immediately after installing it will throw a JS error about the element being undefined. Maybe we could trigger a page refresh after the install to get around that?

2024-08-03 01:18 UTC, jaredrethman commented
> Works well after a page refresh, but since some of the settings sections aren't rendered if we don't have the plugin requirements, if you click "Configure" immediately after installing it will throw a JS error about the element being undefined. Maybe we could trigger a page refresh after the install to get around that?

Nice catch. Have added `shouldRefreshAfterUpdate` property to both plugin objects.

2024-08-05 17:19 UTC, dkoo approved these changes
Looking good now, thanks for the updates!

2024-08-09 13:25 UTC, merged