Feat/ia setting social  pixel
Automattic/newspack-plugin pull request #3274
Opened 2024-07-24 20:53 UTC by jaredrethman

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-07-30 16:45 UTC, dkoo requested changes
Looking good! Just one question below.

2024-07-30 16:45 UTC, dkoo commented on assets/wizards/newspack/views/settings/social/meta-pixel.tsx
> +					type="number"
Can Meta pixels contain non-alphanumeric characters? The `type="number"` means that if I enter some other character it shows the `Value cannot be empty!` error:

<img width="1059" alt="Screenshot 2024-07-30 at 10 42 33 AM" src="https://github.com/user-attachments/assets/cde81e23-34fb-4a7f-8bd9-8709974a8ecf">

2024-07-30 16:54 UTC, jaredrethman commented on assets/wizards/newspack/views/settings/social/meta-pixel.tsx
> +					type="number"
Well spotted @dkoo , I have removed the `type` attribute

2024-08-30 16:03 UTC, dkoo approved these changes
Working well!

2024-08-30 17:04 UTC, merged