feat(plugins): remove support for publisher-media-kit plugin
Automattic/newspack-plugin pull request #3358
Opened 2024-08-22 08:28 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Removes references to the `publisher-media-kit` plugin, which will be included in `newspack-ads` plugin.

### How to test the changes in this Pull Request:

1. Smoke test

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-09-16 18:24 UTC, kevinzweerink commented
So I would recommend we follow the pattern we established for Everlit here:
https://www.figma.com/design/dvq52oOtkKpwYfKKFnGhUr/Newspack-Plugin?node-id=25960-7859&t=kFTbDOH1BoK2LoD6-1

What you've got is actually pretty close, I would just make a few small tweaks to get it more aligned:

* The un-activated state stays the same as you've implemented
* The intermediate (pending) state keeps the toggle in the off position. The emoji icon should be removed, and I would adjust the copy to say "Media kit page is created but unpublished, click the link to review and publish." And then the link text could be "Review draft page"
* The active state can stay the same (except removing the emoji)

What state is shown if you toggle the card back off once it's fully activated? My recommendation would be that it go back to the pending state. Using the "off" position for the toggle makes more sense that way — otherwise you're toggling between "active" and "disabled" and the toggle can never truly be toggled off.

2024-09-19 11:22 UTC, adekbadek commented
@kevinzweerink – thanks! I've update the code & PR description.

2024-09-19 11:23 UTC, adekbadek commented
@Automattic/newspack-product – this is ready for review now.

2024-09-19 13:57 UTC, leogermani requested changes
Not working as expected for me:

I've deleted the page, and the toggle is disabled and the subtitle is correct, but the link "review draft page" is there with a broken link.

![image](https://github.com/user-attachments/assets/e09291cc-fd32-4a80-b323-445aef115d12)

When I click the toggle, the subtitle changes, but the page is not created. I see this in the logs:

```
PHP Warning:  Undefined array key "query" in /newspack-repos/newspack-plugin/includes/configuration_managers/class-newspack-ads-configuration-manager.php on line 212
```

2024-09-20 09:11 UTC, adekbadek commented
@leogermani – this would happen if you did not switch `newspack-ads` to the corresponding branch (`feat/expose-media-kit`). Nevertheless, I've added some error handling for this case.

2024-09-20 13:36 UTC, leogermani commented
> this would happen if you did not switch newspack-ads to the corresponding branch (feat/expose-media-kit). Nevertheless, I've added some error handling for this case.

I was!

And just confirmed that if I checkout https://github.com/Automattic/newspack-plugin/pull/3358/commits/a70cf525f98aaab0e69259e4147eb54ae185bc24 I still see the error I described.

But now in the latest commit of this branch it works as expected

2024-09-20 13:38 UTC, leogermani approved these changes

2024-09-20 13:38 UTC, leogermani approved these changes

2024-09-20 13:43 UTC, merged