Feat/ia settings display settings  part 2
Automattic/newspack-plugin pull request #3430
Opened 2024-09-17 19:16 UTC by jaredrethman

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-09-20 18:12 UTC, jaredrethman commented on includes/wizards/class-setup-wizard.php
> +			if ( '' !== $value && in_array( $key, $this->media_theme_mods ) ) {
Related - #3433

2024-10-11 17:26 UTC, dkoo requested changes
@jaredrethman all is working well except for a couple of issues I ran into when testing the "update feature image/template for all posts" options.

1. If I make no selection to either dropdown, the request gets sent with these keys with a `none` value, causing the meta field to be updated to `none` for all posts
2. (Not originating in this PR, but related) The query to fetch all posts doesn't account for posts that lack the meta key at all, so these posts aren't updated even if you intend to update all posts.

https://github.com/Automattic/newspack-plugin/pull/3470 fixes both of these issues for me. Definitely open to other ways to handle them, though ,so I'll leave it up to you whether to just merge that or fix in another way.

2024-10-11 18:48 UTC, jaredrethman commented
> #3470 fixes both of these issues for me. Definitely open to other ways to handle, though ,so I'll leave it up to you whether to just merge that or fix in another way.

Have merged you're fix, appreciate you providing that!

2024-10-11 19:25 UTC, dkoo approved these changes

2024-10-14 14:26 UTC, merged