feat(ia-listings): IA for Listings Plugin
Automattic/newspack-plugin pull request #3483
Opened 2024-10-17 20:44 UTC by ronchambers

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This code completes Asana Task: "Newspack Information Architecture > IA Listings".  

Screenshot of Menu:

![ia-listings-changes](https://github.com/user-attachments/assets/9d5f73ca-dc85-48c3-b3aa-36ce9727bb29)

* Menu position and icon updated.
* All sub menu items have the new Admin Header.
* Links to categories/tags removed.
* Link for Marketplace moved above Generic ( SEE RELATED: https://github.com/Automattic/newspack-listings/pull/487 )

Screenshot of Dashboard:

![ia-listings-dashboard](https://github.com/user-attachments/assets/aa94b045-497b-4857-afcc-1300abed525d)

* "Cards" are clickable to Listings menu items.
* When Listings Plugin is inactive, entire section and cards are removed.

### How to test the changes in this Pull Request:

1. Pull branch.
2. `npm run build`
3. Activate Newspack plugin.
4. Install/activate Newspack Listings Plugin.
5. Verify screenshots and notes above.
6. Deactivate Listings plugin, verify dashboard no longer shows Listings section.

### Note about Related PR:

The code to move the submenu link for Marketplace above Generic is done in the Listings Plugin. ( SEE RELATED: https://github.com/Automattic/newspack-listings/pull/487 ) 

If we are unable to approve that PR, then we'll need to approve this PR keeping Generic above Marketplace (this is how Listings Plugin does it already), or we'll need to update this PR with a solution.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-10-24 05:05 UTC, ronchambers commented
@miguelpeixe - please see above. I'll assign you in Asana and reach out in Slack.

2024-10-24 14:49 UTC, miguelpeixe requested changes
It tested well! I have just a minor request inline.

2024-10-24 14:49 UTC, miguelpeixe commented on includes/wizards/class-listings-wizard.php
> +		if ( ! is_plugin_active( 'newspack-listings/newspack-listings.php' ) ) {
```suggestion
		if ( ! defined( 'NEWSPACK_LISTINGS_FILE' ) ) {
```

The path check is a bit fragile. It's not uncommon to use a different path when using a custom version for testing or other reasons.

2024-10-24 14:49 UTC, miguelpeixe commented on includes/wizards/newspack/class-newspack-dashboard.php
> +		if ( is_plugin_active( 'newspack-listings/newspack-listings.php' ) ) {
```suggestion
		if ( defined( 'NEWSPACK_LISTINGS_FILE' ) ) {
```

Same as the other comment.

2024-10-24 16:05 UTC, ronchambers commented on includes/wizards/class-listings-wizard.php
> +		if ( ! is_plugin_active( 'newspack-listings/newspack-listings.php' ) ) {
Agreed!

2024-10-24 16:05 UTC, ronchambers commented on includes/wizards/newspack/class-newspack-dashboard.php
> +		if ( is_plugin_active( 'newspack-listings/newspack-listings.php' ) ) {
Agreed!

2024-11-01 16:29 UTC, miguelpeixe commented
@jaredrethman I've pushed some changes to accommodate the recent refactor to the menu order logic. Could you review this one?

2024-11-01 22:34 UTC, jaredrethman requested changes
@miguelpeixe thanks for the review, only thing missing is active submenu when add/edit post types i.e:
`/wp-admin/post-new.php?post_type=newspack_lst_*`
`/wp-admin/post.php?post=POST_ID`

2024-11-04 13:44 UTC, miguelpeixe commented
Thank you for catching that, @jaredrethman!

Fixed in e6fbff0694a0457f54fcb6aa6b3bfbace71275a3

2024-11-05 14:35 UTC, jaredrethman approved these changes
@miguelpeixe thanks for the updates - code looks good - approved!

2024-11-05 15:47 UTC, merged