Feat/ia audience
Automattic/newspack-plugin pull request #3500
Opened 2024-10-25 14:41 UTC by jaredrethman

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

### How to test the changes in this Pull Request:

1.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-11-06 20:28 UTC, jaredrethman commented on src/admin/style.scss
> +.newspack-wizard__content:has(> .newspack-wizard__sections) {
Only apply styling to wizards wrapping components in `WizardsTab` component. See [example](https://github.com/Automattic/newspack-plugin/blob/feat/ia-audience/src/wizards/audience/views/configuration/settings.js#L164)

2024-11-14 14:25 UTC, miguelpeixe requested changes
This is looking great! All RAS configuration steps are working as expected.

When finishing the configuration, the prompts configuration didn't trigger the activation of RAS. It just redirected back to the steps with the  "Reader Activation Campaign" as pending:

https://github.com/user-attachments/assets/558e944e-9ea0-488a-b37c-6bd699208a19

---

The Audience parent menu was mislocated, I pushed f4330270bd16de033c1cc9b6c9d250b86ea37c7a to fix the order:

<img width="189" alt="image" src="https://github.com/user-attachments/assets/673395ed-b27b-4efd-babf-81a0f35436bf">

---

When editing audience-related content (transactional emails and membership gate), we want "Audience -> Configuration" as the current menu. I pushed 41af6592ad9b5e372fcb11982ea3fccd10ff954e to fix that:

| Membership Gate | Email |
| --- | --- |
| <img width="1096" alt="image" src="https://github.com/user-attachments/assets/f1e95147-ef43-4150-82c2-3c2509730638"> | <img width="1094" alt="image" src="https://github.com/user-attachments/assets/6871da8d-0789-4d77-b257-75ed3675fceb"> |

---

On another note, do you mind deleting the duplicated files source? We don't need the previous wizards working. This will help with the cleanup and a more comprehensive diff.

2024-11-14 17:25 UTC, ronchambers commented
FYI: I merged `epic/ia` (to get the updated [menu priority](https://github.com/Automattic/newspack-plugin/pull/3544) fixes), then I updated the parent menu vars in this commit: https://github.com/Automattic/newspack-plugin/pull/3500/commits/d87d0ab3d3e48be1fc31e35fb4acb6d01e48dce2

Parent menu order:

![image](https://github.com/user-attachments/assets/92960c81-fa8c-435c-ace0-aecae7e75768)

2024-11-14 17:59 UTC, miguelpeixe commented
> On another note, do you mind deleting the duplicated files source? We don't need the previous wizards working. This will help with the cleanup and a more comprehensive diff.

Pushed 4ea5532f8d53515fa0862e2424c5dab5faf1bb35 and 2740cf703fb508e813232244aa4b3b088e17390c to remove duplicate code

2024-11-14 19:15 UTC, miguelpeixe commented
> When finishing the configuration, the prompts configuration didn't trigger the activation of RAS. It just redirected back to the steps with the "Reader Activation Campaign" as pending:

This was caused by a small issue with the "Continue" button href. The `newspackAudienceConfiguration.reader_activation_url` has a trailing slash and `href={ `${ reader_activation_url }/complete` }` generates `href="[...]?page=newspack-audience-configuration#//complete"`, which doesn't work. Fixed in f572a659e714f5d8d91b662fb48b05c44f31d371

2024-11-14 19:20 UTC, miguelpeixe commented
This looks good to me. Since I pushed a few changes, @ronchambers, do you mind reviewing this?

2024-11-18 23:45 UTC, ronchambers commented
@miguelpeixe @jaredrethman  - I tested locally and everything seems to work as expected.  My react skills aren't good enough to do an approval, and I don't know Audience/RAS well enough to know what edge cases might be, but I did get though the initial configuration and then the RAS campaign setup too without any issues.  Looks good!  😃

2024-11-19 22:30 UTC, jaredrethman commented
@miguelpeixe @ronchambers thanks for the updates and reviews to this PR. I've gone through all the updates and am happy with the progress/changes that have been made. Can we go ahead and approve+merge?

2024-11-20 00:22 UTC, ronchambers approved these changes
Since @miguelpeixe said it looks good and Ron tested too, approved.  @jaredrethman ok to merge.

2024-11-20 03:09 UTC, merged