feat(plugins): add url redirect for wc subscription renewals
Automattic/newspack-plugin pull request #3525
Opened 2024-11-05 21:44 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://app.asana.com/0/1206274567818686/1208437232706180/f

This PR adds handling for a `np_renewal` param to redirect readers to the first available pending renewal checkout:

![Screenshot 2024-11-05 at 16 39 08](https://github.com/user-attachments/assets/733544ac-979d-40f9-9276-fe392227dfa6)

### How to test the changes in this Pull Request:

1. As admin, go to any subscription edit page via WooCommerce Subscriptions
2. Create a renewal order for the subscription
![Screenshot 2024-11-05 at 16 41 21](https://github.com/user-attachments/assets/306ebe26-daa6-4d02-a938-d59d082604b7)
3. As the logged in reader, visit your test site with the `np_renewal` param appended to the url: `site.url?np_renewal`
4. Confirm you are redirected to checkout for the renewal order in question
5. Complete checkout to re-activate the subscription
6. Visit the url from step 3 again.
7. Confirm you are not redirected this time
8. Log out
9. Visit the url from step 3 again.
10. Confirm you are not redirected.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-11-06 23:22 UTC, chickenn00dle commented on src/reader-activation/auth.js
> +							if ( ! redirectInput?.value ) {
We should respect any pre-defined redirect values.

2024-11-06 23:23 UTC, chickenn00dle commented on src/reader-activation/auth.js
> +			if ( ev?.target?.getAttribute( 'data-redirect' ) && ! redirectInput?.value ) {
Same here re: respecting pre-defined redirect values

2024-11-07 20:12 UTC, chickenn00dle commented
Got some feedback here so removing the `Needs Review` label to work on this: 0-as-1208437232706180/1208702687864921/f

2024-11-14 17:03 UTC, chickenn00dle commented
Added some changes to make the redirect happen via a new my-account endpoint `my-renewals`. Also updated the testing instructions. 

Just awaiting feedback to verify the expected behavior before marking this one ready for review.

2024-11-25 18:59 UTC, dkoo approved these changes
Working well! Conditionally approved, with just a couple of questions:

1. I had to refresh permalinks before the new endpoint would redirect. Is there anything we need to do to ensure this happens automatically with no downtime for live sites?
2. Based on the discussion in https://github.com/Automattic/newspack-plugin/pull/3560#issuecomment-2498249591 it sounds like we're moving to a `woocommerce-subscriptions` directory with smaller classes inside, so should we refactor to this structure here to avoid a future conflict? This could probably just be moved to the `woocommerce-subscriptions` directory since it's fairly self-contained.

2024-11-26 20:04 UTC, leogermani requested changes
as per @dkoo review, we need to add a rewrite rule refresh to be execute once after this change is deployed. Also agree with his comment on the file structure.

And just to confirm that naming things is one of the hardest problems in computes science. WDYT of `renew-subscription` or `subscription-renew` (in the singular form, because that's the main intent of this link, redirect to Subscriptions is a fallback)

2024-11-27 16:13 UTC, chickenn00dle commented
Thanks for the feedback @leogermani and @dkoo!

> we need to add a rewrite rule refresh to be execute once after this change is deployed. Also agree with his comment on the file structure.

Flushed permalinks and reorganized in https://github.com/Automattic/newspack-plugin/pull/3525/commits/fa7cdc2fc45c25e07d31ddb922f6766c6a8e5262

> And just to confirm that naming things is one of the hardest problems in computes science. WDYT of renew-subscription or subscription-renew (in the singular form, because that's the main intent of this link, redirect to Subscriptions is a fallback)

I like `renew-subscription`! I went with that in https://github.com/Automattic/newspack-plugin/pull/3525/commits/fa7cdc2fc45c25e07d31ddb922f6766c6a8e5262

2024-11-27 20:22 UTC, leogermani commented
This looks good and works nicely.

One question though. My expectation was - I think it would be awesome - that if I'm not logged in and visit `renew-subscription`, I will be redirected to the checkout page, the same thing that happens when I'm logged in. Do you think that's possible?

2024-11-27 21:14 UTC, chickenn00dle commented
> that if I'm not logged in and visit renew-subscription, I will be redirected to the checkout page, the same thing that happens when I'm logged in. Do you think that's possible?

We can accomplish this by adding a redirect param with a value of the new endpoint and handling this when rendering the auth form. Added in https://github.com/Automattic/newspack-plugin/pull/3525/commits/a01a0b5ba429ec9504f286c497aed2f74fa71fa4

Let me know what you think!

2024-11-28 13:55 UTC, leogermani approved these changes

2024-12-02 21:41 UTC, merged