refactor(ia): audience development setup and tabs
Automattic/newspack-plugin pull request #3559
Opened 2024-11-20 17:03 UTC by miguelpeixe

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-11-20 22:34 UTC, jaredrethman requested changes
@miguelpeixe thank you for the refactor, I think its much better. I made one suggestion below to fix RAS skipping endpoint.

One other nitpick - in `src/wizards/audience/views/setup/content-gating.js` inside a `useEffect` hook there's `window.scrollTo( 0, 0 );`, should we have these in other tab components for consistency (I've also seen the same `scrollTo` code in setup)? If you agree I've prepared a [solution](https://github.com/Automattic/newspack-plugin/compare/epic/ia-audience-setup-tabs...feat/ia-audience-setup-tabs__scroll-to) for you to see/use.

2024-11-20 22:34 UTC, jaredrethman commented on src/wizards/audience/views/setup/campaign.js
> +				path: '/newspack/v1/wizard/newspack-audience/reader-activation/skip-campaign-setup',
```suggestion
				path: '/newspack/v1/wizard/newspack-audience/reader-activation/skip-campaign',
```

2024-11-21 12:44 UTC, miguelpeixe commented on src/wizards/audience/views/setup/campaign.js
> +				path: '/newspack/v1/wizard/newspack-audience/reader-activation/skip-campaign-setup',
Thank you for catching that!

2024-11-21 12:57 UTC, miguelpeixe commented
> One other nitpick - in src/wizards/audience/views/setup/content-gating.js inside a useEffect hook there's window.scrollTo( 0, 0 );, should we have these in other tab components for consistency (I've also seen the same scrollTo code in setup)? If you agree I've prepared a DRY [solution](https://github.com/Automattic/newspack-plugin/compare/epic/ia-audience-setup-tabs...feat/ia-audience-setup-tabs__scroll-to) for you to see/use.

The content gating inherited the `scrollTo()` from the `setup.js`. There's no need for it because there's no redirect back to that wizard, as there can be throughout the setup steps.

I think the wizard feature you propose might be overkill for now. I removed the call in 205d4fad912835588a19572a1f82fe9155f8e648

2024-11-21 14:19 UTC, jaredrethman commented
> I think the wizard feature you propose might be overkill for now...

Got it. The same code can be seen in the Setup component. Although it might be there for a different reason!?
https://github.com/Automattic/newspack-plugin/blob/205d4fad912835588a19572a1f82fe9155f8e648/src/wizards/audience/views/setup/setup.js#L38-L42

2024-11-21 14:20 UTC, jaredrethman approved these changes

2024-11-21 14:22 UTC, miguelpeixe commented
It exists in the `setup.js` because of the [handoff redirects](https://github.com/Automattic/newspack-plugin/blob/205d4fad912835588a19572a1f82fe9155f8e648/src/wizards/audience/components/prerequisite.tsx#L138-L167)/

2024-11-21 14:22 UTC, miguelpeixe commented
Thanks for the review, @jaredrethman!

2024-11-21 14:23 UTC, merged