feat(corrections): add corrections and clarifications behind feature flag
Automattic/newspack-plugin pull request #3638
Opened 2024-12-18 20:53 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2025-01-07 23:01 UTC, chickenn00dle commented
TODO:

- [ ] Update corrections
- [ ] Refresh on corrections submit

2025-01-08 22:33 UTC, chickenn00dle commented on src/other-scripts/corrections/index.js
> +} );
This is a super hacky way to force reload the page. We need to reload the page when adding new corrections so the metabox fields can repopulate with the respective correction ids (needed for updates and deleting)

2025-01-08 22:35 UTC, chickenn00dle commented
Gonna mark this one ready for review since the core funcitonality is working and this should at least get us to a point where we can begin migrating corrections.

2025-01-09 15:41 UTC, leogermani requested changes
It works and serves the purpose of unblocking migration.

There is just one warning being thrown at `delete_corrections` method.

I left a few other non blocking comments

Another non-blocking comment: I think "activate corrections" and "position" should be a global setting, and not something per post... We can discuss it and I don't think this will be a blocker for migration now.... well... maybe we can get rid of the "activate" so it doesn't get in the way.

Finally, WDYT of adding a short README to the folder describing how the data is stored, to inform LEs that will work on the migration?

2025-01-09 15:41 UTC, leogermani commented on includes/corrections/class-corrections.php
> +		$stored_correction_ids = get_post_meta( $post_id, self::CORRECTIONS_IDS_META, true );
`$post_id` doesn't seem to be defined here

2025-01-09 15:41 UTC, leogermani commented on includes/corrections/class-corrections.php
> +			'show_ui'          => true,
I don't think we want the UI for that

2025-01-09 15:41 UTC, leogermani commented on includes/corrections/class-corrections.php
> +						self::CORRECTION_DATE_META    => $correction['date'],
why not store the date using post_date?

2025-01-09 15:41 UTC, leogermani commented on includes/corrections/class-corrections.php
> +	public static function save_corrections( $post_id, $corrections ) {
nit: naming it `add_corrections` (or insert) would make the purpose of this method clearer

2025-01-09 16:50 UTC, chickenn00dle commented on includes/corrections/class-corrections.php
> +		$stored_correction_ids = get_post_meta( $post_id, self::CORRECTIONS_IDS_META, true );
Oops! Good catch. Fixed in https://github.com/Automattic/newspack-plugin/pull/3638/commits/fea98909ba23a62584c9f97bd3a2adc97bf1be2e

2025-01-09 16:50 UTC, chickenn00dle commented on includes/corrections/class-corrections.php
> +			'show_ui'          => true,
Also fixed in https://github.com/Automattic/newspack-plugin/pull/3638/commits/fea98909ba23a62584c9f97bd3a2adc97bf1be2e

2025-01-09 16:53 UTC, chickenn00dle commented on includes/corrections/class-corrections.php
> +						self::CORRECTION_DATE_META    => $correction['date'],
I thought about this, but also considered corrections will be viewed in other contexts outside of a post (shortcode, archive, etc.) and so it might be useful to distinguish between the actual date a correction is published and the date assigned to a correction by a publisher as these might not always be the same.

2025-01-09 16:53 UTC, chickenn00dle commented on includes/corrections/class-corrections.php
> +	public static function save_corrections( $post_id, $corrections ) {
Good suggestion! I am not very good at naming things. Fixed in https://github.com/Automattic/newspack-plugin/pull/3638/commits/fea98909ba23a62584c9f97bd3a2adc97bf1be2e

2025-01-09 16:57 UTC, chickenn00dle commented
Thanks for the review @leogermani!

> Another non-blocking comment: I think "activate corrections" and "position" should be a global setting, and not something per post... We can discuss it and I don't think this will be a blocker for migration now.... well... maybe we can get rid of the "activate" so it doesn't get in the way.

I think position makes sense as a global setting, but do think it would be useful for publishers to be able to set whether corrections are active at the post level. For example, being able to publish a correction but not set it to active until it has been approved/verified. That said, I am open to any decision here.

> Finally, WDYT of adding a short README to the folder describing how the data is stored, to inform LEs that will work on the migration?

Great idea! Added one here: https://github.com/Automattic/newspack-plugin/blob/fea98909ba23a62584c9f97bd3a2adc97bf1be2e/includes/corrections/README.md

Let me know if I need to expand anywhere!

2025-01-09 17:20 UTC, leogermani commented on includes/corrections/class-corrections.php
> +						self::CORRECTION_DATE_META    => $correction['date'],
Right, I actually thought that the date the correction was posted is not relevant, so we could use this field as the correction date.. no need to have two.

But I get your point. The only thing is that if we go this route, `get_corrections` will have to order posts by a postmeta value, that will be a string. If we used the post_date this would be working out of the box

2025-01-09 17:24 UTC, leogermani commented
> For example, being able to publish a correction but not set it to active until it has been approved/verified. That said, I am open to any decision here.

Makes sense. We don't need to decide this now, it has little impact on the migration. Can I just suggest that this should be active by default?

I'm thinking about LEs migrating data and wanting to look at the site to see if the data is there. Ideally they wouldn't need to add a "active = true" for every post and we'll think about it later

2025-01-09 18:30 UTC, chickenn00dle commented on includes/corrections/class-corrections.php
> +						self::CORRECTION_DATE_META    => $correction['date'],
That's a fair point. I've updated this to use `post_date` instead in https://github.com/Automattic/newspack-plugin/pull/3638/commits/13dbe298c90b8fd99b6766138d43d8a3cb91179d

2025-01-09 18:31 UTC, chickenn00dle commented
> Makes sense. We don't need to decide this now, it has little impact on the migration. Can I just suggest that this should be active by default?

> I'm thinking about LEs migrating data and wanting to look at the site to see if the data is there. Ideally they wouldn't need to add a "active = true" for every post and we'll think about it later

That's fair. I've updated this in https://github.com/Automattic/newspack-plugin/pull/3638/commits/0017f165072eeff547e70d7efd5fc08893749b88 so when the meta is not present corrections will be shown.

2025-01-09 20:22 UTC, leogermani approved these changes
Thanks for the revisions!

2025-01-11 14:38 UTC, merged

2025-01-11 14:50 UTC, chickenn00dle commented
Removing needs-changelog label since this feature is strictly to prep for a migration and won't actually launch quite yet