chore: add Newspack Listings as a whitelisted plugin
Automattic/newspack-plugin pull request #749
Opened 2020-12-17 01:05 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds Newspack Listings as a whitelisted plugin for easy manual installation. Happy to take feedback on the description copy.

### How to test the changes in this Pull Request:

1. Check out this branch and run `npm run release:archive`.
2. Install and activate the .zip that's generated in `/assets/release/newspack-plugin.zip` to a new test site.
3. Complete the onboarding steps as usual (can skip the Jetpack and Site Kit setup).
4. Go to **Plugins** and verify that Newspack Listings is listed and can be installed with a button click.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2020-12-17 23:30 UTC, jeffersonrabb requested changes
Just need to change the download link - it was still the one for Newspack Plugin.

2020-12-17 23:30 UTC, jeffersonrabb commented on includes/class-plugin-manager.php
> +				'Download'    => 'https://github.com/Automattic/newspack-plugin/releases/latest/download/newspack-plugin.zip',
```suggestion
				'Download'    => 'https://github.com/Automattic/newspack-listings/releases/latest/download/newspack-listings.zip',
```

2020-12-18 21:50 UTC, dkoo commented
> Just need to change the download link - it was still the one for Newspack Plugin.

🤦 Doh! Updated in 1f5b3fd.

2020-12-18 21:51 UTC, jeffersonrabb approved these changes
👍

2020-12-18 21:56 UTC, merged