feat: campaign group filter with preview
Automattic/newspack-plugin pull request #771
Opened 2020-12-31 17:24 UTC by jeffersonrabb

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds preview functionality to the Campaigns Wizard Campaigns tab. At some point this functionality may make the Preview tab unnecessary, however the new approach doesn't support selecting multiple Campaign Groups so I'm leaving it untouched for now.

Dependent PRs:
https://github.com/Automattic/newspack-plugin/pull/764
https://github.com/Automattic/newspack-plugin/pull/767
https://github.com/Automattic/newspack-plugin/pull/768
https://github.com/Automattic/newspack-plugin/pull/769
https://github.com/Automattic/newspack-plugin/pull/770

<img width="1420" alt="Screen Shot 2020-12-31 at 12 14 54 PM" src="https://user-images.githubusercontent.com/1477002/103419720-356ac500-4b62-11eb-82c8-44a48696f46d.png">

### How to test the changes in this Pull Request:

1. Be sure you have created some Campaign Groups and Segments.
2. Navigate to Campaign Wizard, first tab. 
3. Select a Campaign Group. Observe the "Segment to preview" `SelectControl` is shown. 
4. Select a Segment and click Preview, observe normal preview functionality.
5. Compare various preview scenarios in Preview and Campaigns tabs, verify the results are identical.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-01-04 15:34 UTC, jeffersonrabb commented
UI changes from https://github.com/Automattic/newspack-plugin/pulls merged into this branch. Per discussion with @thomasguillot preview is now a `Button` that reveals a `Popover` with the segmentation `SelectControl` in it.  Change made in https://github.com/Automattic/newspack-plugin/pull/771/commits/d45da835f8fd7b483028d5838b176624d0ac2c1c. I've done no styling - handing this over to @thomasguillot for that.

2021-01-04 17:43 UTC, thomasguillot commented
@jeffersonrabb pushed some css changes in https://github.com/Automattic/newspack-plugin/pull/771/commits/5769beac561c65b11809520f54576fb4bd01a5ca

2021-01-05 01:12 UTC, dkoo reviewed
Looks good from functional testing. Awaiting conflict resolution to complete review.

2021-01-05 19:00 UTC, jeffersonrabb commented
> Looks good from functional testing. Awaiting conflict resolution to complete review.

Conflicts resolved, ready for review @dkoo!

2021-01-05 21:02 UTC, dkoo requested changes
Almost there, just found a lost `console.log` wandering about.

2021-01-05 21:02 UTC, dkoo commented on assets/wizards/popups/views/popup-group/index.js
> +													console.log( showPreview );
Errant `console.log`?

2021-01-05 22:12 UTC, jeffersonrabb commented on assets/wizards/popups/views/popup-group/index.js
> +													console.log( showPreview );
Whoops! https://github.com/Automattic/newspack-plugin/pull/771/commits/a44e7062b638683c72dd99850af1eed569c529b4

2021-01-05 22:55 UTC, dkoo approved these changes
Looks good now!

2021-01-05 23:52 UTC, merged