[WIP] feat: activate and deactivate are bulk publish controls
Automattic/newspack-plugin pull request #799
Opened 2021-01-08 04:19 UTC by dkoo

Instead of using an "active" group, campaigns are displayed on the front-end if they are published and if they belong to a segment matching the current reader.

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

A proof-of-concept. Like in #775, introduces the concept of bulk-activating and deactivating campaigns by group. Unlike #775, this branch uses the WP post status of campaigns to determine whether or not individual campaigns should be shown on the front-end, and turns "Activate" and "Deactivate" buttons into bulk publish/unpublish actions that apply to the currently viewed campaigns. "Activating" campaigns when viewing a particular group of campaigns will publish any unpublished campaigns in that group and also automatically unpublish all campaigns that don't belong to the viewed group.

Note that for test purposes I've removed labels for Test and "Never" frequency campaigns and ignored those criteria when displaying campaigns in anticipation of #776, but I did not fully deprecate all functionality for those statuses here.

### How to test the changes in this Pull Request:

1. View the Campaigns tab in the wizard. Confirm that the filter always defaults to the "All campaigns" filter view.
2. Confirm that published campaigns are shown with a green label and unpublished campaigns (draft, pending or scheduled) are shown with a grey label.
3. Expand the popover menu for a published campaign. Confirm that there's a new "Unpublish" option that when clicked, reverts the selected campaign to draft status.
4. Observe the "Publish All", "Unpublish All" and "Preview" buttons that are now visible in the All Campaigns filter view.
5. Click "Publish All" and confirm that this sets ALL campaigns to "publish" status. Then click "Unpublish All" and confirm that it sets ALL campaigns to "draft" status.
6. Filter the campaigns list by a group. Click "Publish All" and confirm that this sets only the campaigns in this group to "publish" status. (Make sure to view another group to confirm that those campaigns are still in draft status).
7. View another group and click "Publish All". Confirm that the campaigns in this group are now set to "publish" status, and campaigns in the first group that don't exist in this second group are set to "draft" status.
8. Preview various groups and segments and confirm that preview still works as expected, with the caveat that draft, pending, scheduled and published campaigns are all shown in the preview modal. (Note that this won't work in the wizard Preview tab—I'll have to address that if we decide to move ahead with this proof of concept).
9. View the site front-end in a new incognito window and confirm that only published campaigns matching the reader's segment are shown.
10. The one caveat to (9) is that campaigns that are set to "Uncategorized" are now able to show with any category—this seems more intuitive to me, especially since uncategorized posts are automatically assigned the "Uncategorized" category when published.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-01-09 16:38 UTC, thomasguillot commented
@dkoo in https://github.com/Automattic/newspack-plugin/pull/799/commits/a982bb0576f0f1531537b8b119b2f9476333a20b and https://github.com/Automattic/newspack-plugin/pull/799/commits/ab970b4b96053342a462f6949541cc2bb221fcce I pushed a few visual changes to your PR. I thought it was better to do it directly here rather than creating a new PR later on.

2021-01-11 04:11 UTC, jeffersonrabb requested changes
This is working well - left a few comments.

2021-01-11 18:36 UTC, dkoo commented on assets/wizards/popups/index.js
> +			path: addQueryArgs( '/newspack/v1/wizard/newspack-popups-wizard/campaign-group/', {
Good idea, updated in 85f2335.

2021-01-11 18:36 UTC, dkoo commented on includes/wizards/class-popups-wizard.php
> +			'/wizard/' . $this->slug . '/campaign-group',
Updated in 85f2335.

2021-01-11 18:36 UTC, dkoo commented on includes/wizards/class-popups-wizard.php
> +		register_rest_route(
Updated in 85f2335.

2021-01-11 22:21 UTC, jeffersonrabb approved these changes
Looks good! You'll have some merge conflicts, and there are a couple small bits you'll be able to remove (e.g. the localstorage part of previewing). Also, I'd suggest renaming `activate_campaign_group` and `deactivate_campaign_group` everywhere (configuration manager and `newspack-popups`) just to avoid confusion, but that won't require another review.

2021-01-11 22:34 UTC, dkoo commented
Renamed the `activate_campaign_group` and `deactivate_campaign_group` functions and fixe conflicts in 56562bb. Thanks!

2021-01-11 22:43 UTC, merged