fix: change in how to retrieve property id from site kit
Automattic/newspack-plugin pull request #849
Opened 2021-02-04 16:41 UTC by jeffersonrabb

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

A small change in Site Kit 1.25.0 breaks the cross domain tracking handling on AMP pages. This PR resolves it.

### How to test the changes in this Pull Request:

1. Install Site Kite 1.24.0 (e.g. `wp plugin install google-site-kit --version=1.24.0 --force`) and switch `newspack-plugin` to `master`. Put the site in AMP Transitional mode.
2. Set Reader Revenue wizard to News Revenue Hub, use an organization ID from a production site.
3. Add Donate block to a post.
4. View the post (non-AMP), choose a price, click to submit the form. Observe `_gl` parameter with a long random string in the URL.
5. Do the same in non-AMP. Observe there are two identical `_gl` parameters (a Site Kit bug).
6. Upgrade Site Kit to 1.25.0.
7. Repeat the non-AMP flow. Observe there is no longer a `_gl` parameter. 
8. Switch `newspack-plugin` to this branch, try the non-AMP flow again. Observe the `_gl` parameter is back and there is only one. All problems are solved!

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-02-04 21:07 UTC, dkoo requested changes
Hmm, maybe I'm not understanding something in the testing instructions, but I'm not seeing what you describe. Here's what I saw:

On `master` on v1.24.0:

1. Viewed the post with Donate block in AMP mode, clicked through to the NRH landing page. I see no `_gl` parameter on the URL.
2. Viewed the post with Donate block in non-AMP mode, clicked through to the NRH page. I still see no `_gl` param, but I do see a single `_ga` parameter that looks like this: `&_ga=2.265024583.959187778.1612471267-amp-idRLw1eg69qUpGndQNHNrQ`
3. Viewed the post in non-AMP mode again, clicked through, still saw no `_gl` param and a single `_ga` param.
4. Updated Site Kit to v1.25.0.
5. Repeated steps 1 and 2 with the same results—no `_gl` param at any point, a `_ga` param only when clicking through from non-AMP.
6. Switched to this branch, repeated steps 1-5 and saw no difference in behavior.

At no point did I ever see  `_gl` param or more than one `_ga` param. What am I doing wrong?

2021-02-04 21:09 UTC, jeffersonrabb commented
> What am I doing wrong?

Is Google Analytics set up for the site (through Site Kit)?

2021-02-09 08:40 UTC, adekbadek approved these changes
(Note: this is the same fix as in https://github.com/Automattic/newspack-plugin/pull/846)

2021-02-10 02:14 UTC, dkoo commented
@jeffersonrabb Did you get a response from the Google folks about why the param is sometimes `_gl` and sometimes `_ga`, and missing completely at other times?

2021-02-10 16:51 UTC, dkoo approved these changes
Approving this because it shouldn't break anything—only potentially fix issues for some.

2021-02-10 20:28 UTC, merged