fix: preview functionality by campaign/group
Automattic/newspack-plugin pull request #856
Opened 2021-02-10 03:30 UTC by dkoo

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-02-10 17:50 UTC, adekbadek requested changes
1. When previewing a segment with a prompt which has a category condition set, the prompt is not visible. After removing the category, the prompt is visible in the preview.
2. A prompt segmented to donors is showing up in the "Everyone" segment preview (both when previewing a campaign, and active prompts, regardless of whether the prompt is assigned to a campaign).

2021-02-10 18:49 UTC, dkoo commented
> 1. When previewing a segment with a prompt which has a category condition set, the prompt is not visible. After removing the category, the prompt is visible in the preview.

This is actually kind of working as intended—when previewing a prompt with category filtering, the prompt will only appear on posts that match its category. The problem is that the preview URL is just the latest post or the homepage of the site, and it's used for all preview links, so I'm not sure how we'd force it to open a post with matching category for these prompts. Or, do we fudge it and just show category-filtered prompts on any page when previewing?

> 2. A prompt segmented to donors is showing up in the "Everyone" segment preview (both when previewing a campaign, and active prompts, regardless of whether the prompt is assigned to a campaign).

This is fixed in a3a63c6 and https://github.com/Automattic/newspack-popups/pull/438/commits/83136ed4292c718572d2d684bea12d815472e238 in the other repo. Previously when previewing "Default/no segment" it assumed you were previewing as the base segment, which would match every segment and thus show all prompts. So this is a bit of a conceptual shift, although one that makes more sense to me and one that moves more toward the non-cascading segment behavior that we're planning to implement.

2021-02-10 21:47 UTC, jeffersonrabb approved these changes
LGTM

2021-02-10 23:31 UTC, merged

2021-02-11 11:24 UTC, adekbadek commented
> The problem is that the preview URL is just the latest post or the homepage of the site, and it's used for all preview links, so I'm not sure how we'd force it to open a post with matching category for these prompts. 

That would not be a complete solution: you can have a segment with prompts assigned to multiple categories.

> Or, do we fudge it and just show category-filtered prompts on any page when previewing?

That's what I propose https://github.com/Automattic/newspack-popups/pull/441