Starter content removal
Automattic/newspack-plugin pull request #864
Opened 2021-02-15 11:27 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Starter content removal.

### How to test the changes in this Pull Request:

1. Visit the Setup wizard on a fresh site (`/wp-admin/admin.php?page=newspack-setup-wizard#/`)
2. After completing the setup, observe a "Remove Starter Content" link at the bottom of the Newspack dashboard; click it
3. Observe that the starter content has been removed

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-02-16 22:31 UTC, dkoo requested changes
Works perfectly. I have a couple of suggestions:

* Since this is a destructive action, should we make the user confirm that they actually want to proceed? e.g. click "Remove starter content," the browser shows a system prompt saying "All Newspack starter posts, pages, and categories will be deleted. Are you sure you want to proceed?" [OK / Cancel]
* After clicking the button, you get dumped back to the Newspack dashboard page with no visual indication that anything has happened. Maybe we should show a notice at the top of the page here that indicates success ("Starter content deleted.") or failure (if any errors cause some starter content to not be fully deleted).

2021-02-17 17:22 UTC, adekbadek commented
> Since this is a destructive action, should we make the user confirm that they actually want to proceed? 

I don't think that's necessary, this content is meant to be short-lived.

> After clicking the button, you get dumped back to the Newspack dashboard page with no visual indication that anything has happened.

Added a notice in 2152aa74ba135525f1450187368cec17426a0b24

2021-02-17 18:29 UTC, dkoo commented
Hmm, after updating my branch, I'm getting the following JS error whenever I visit the dashboard: 

```
react-dom.min.js?ver=16.13.1:125 TypeError: Object(...) is not a function
    at GlobalNotices (index.js:20)
```

This is true even after re-running `npm install` in the repo root and in `src/components`.

2021-02-17 19:21 UTC, adekbadek commented
> Hmm, after updating my branch, I'm getting the following JS error whenever I visit the dashboard:

Can't reproduce, can you set up an ephemeral site with the bug occurring?

2021-02-18 09:25 UTC, adekbadek commented
@dkoo Thanks for catching that, should be fixed by d36154b917c7912fda117c16067469fb0f7fa33a

2021-02-18 17:15 UTC, dkoo approved these changes
Just a minor nit on the language of the notice, otherwise this is working great now. Feel free to merge whether or not you take the suggestion.

2021-02-18 17:15 UTC, dkoo commented on includes/class-newspack.php
> +			$redirect_url = add_query_arg( 'newspack-notice', __( 'Removed Starter Content', 'newspack' ), $redirect_url );
```suggestion
			$redirect_url = add_query_arg( 'newspack-notice', __( 'Starter content removed.', 'newspack' ), $redirect_url );
```

2021-02-19 10:09 UTC, merged